name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Thanks @${{ github.actor }} for creating your first issue in logi 🎉 "
          pr-message: "Awesome @${{ github.actor }} you created your first PR in lofi 🎉"
